const createTableQuery = {
  addAsset: `CREATE TABLE IF NOT EXISTS asset (
    asset_id INT AUTO_INCREMENT PRIMARY KEY,
    tenant_id INT NOT NULL,
    source_app VARCHAR(50) NOT NULL,
    reference_type VARCHAR(50) NOT NULL,
    reference_id VARCHAR(100) NOT NULL,
    asset_code VARCHAR(50),
    serial_number VARCHAR(100),
    model_number VARCHAR(100) NULL,
    asset_name VARCHAR(100) NOT NULL,
    asset_type VARCHAR(50),
    category VARCHAR(50),
    manufacturer VARCHAR(50),
    asset_status VARCHAR(50),
    asset_condition VARCHAR(50),
    quantity INT,
    price DECIMAL(10,2),
    asset_photo VARCHAR(255),
    asset_images TEXT, -- renamed from asset_images
    year_of_manufacturing YEAR NULL,
    appreciating TINYINT(1) DEFAULT 1,
    depreciating  TINYINT(1) DEFAULT 1,
    next_service_date DATE NULL,
    colour VARCHAR(50) NULL,
    contact_name_number VARCHAR(150) NULL,
    insurance_number VARCHAR(100) NULL,
    insurance_provider VARCHAR(100) NULL,
    insurance_end_date DATE NULL,
    description TEXT,
    allocated_to VARCHAR(100),
    purchased_date DATE,
    purchased_by VARCHAR(50),
    vendor_name VARCHAR(100),
    warranty_expiry DATE,
    expired_date DATE,
    invoice_number VARCHAR(50),
    location VARCHAR(100),
    remarks TEXT,
    created_by VARCHAR(30) NOT NULL DEFAULT 'ADMIN',
    created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(30),
    updated_time TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_tenant (tenant_id),
    KEY idx_reference (reference_type, reference_id),
    KEY idx_asset_code (asset_code),
    KEY idx_status (asset_status)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;`,

  addAssetAllocation: `CREATE TABLE IF NOT EXISTS asset_allocation (
    asset_allocation_id INT AUTO_INCREMENT PRIMARY KEY,
    tenant_id INT NOT NULL,
    asset_id INT NOT NULL,
    asset_allocation_quantity INT(11) NOT NULL,
    reference_type VARCHAR(50) NOT NULL,
    reference_id VARCHAR(100) NOT NULL,
    allocated_to VARCHAR(100),
    allocated_by VARCHAR(100),
    allocation_date DATE,
    expected_return_date DATE,
    actual_return_date DATE,
    status VARCHAR(50),
    remarks TEXT,
    asset_allocation_comments TEXT NULL,
    created_by VARCHAR(30) NOT NULL DEFAULT 'ADMIN',
    created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(30),
    updated_time TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_tenant (tenant_id),
    KEY idx_asset (asset_id),
    KEY idx_reference (reference_type, reference_id),
    KEY idx_status (status)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;`,
   
  addDocumentTable: `
  CREATE TABLE IF NOT EXISTS document (
    document_id INT(11) NOT NULL AUTO_INCREMENT,
    table_name VARCHAR(100) NOT NULL,
    table_id INT(11) NOT NULL,
    field_name VARCHAR(100) NOT NULL,
    file_url VARCHAR(255) NOT NULL,
  
    created_by VARCHAR(30) NOT NULL,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updated_by VARCHAR(30) DEFAULT NULL,
    updated_time TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(),
  
    PRIMARY KEY (document_id),
    INDEX idx_table_reference (table_name, table_id,field_name)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
  `,
};

module.exports = { createTableQuery };
